import "./globals.css";
import { Providers } from "./provider";
import { sohneBold, sohneMono, sohneRegular, sohneSemibold } from "../styles/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <style>
        {`
        :root {
          --font-sohne: ${sohneRegular.style.fontFamily};
          --font-sohne-semibold: ${sohneSemibold.style.fontFamily};
          --font-sohne-bold: ${sohneBold.style.fontFamily};
        }
      `}
      </style>
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
